version: '3.8'

services:

  # rabbitmq:
  #   image: rabbitmq:latest
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   ports:    
  #     - "5672:5672"

  redis:
    image: redis:6-alpine

  backend:
    image: duynguyenngoc/apot:backend
    ports:
      - 8081:8081
    command: uvicorn main:app --host 0.0.0.0 --port 8081 --reload
    volumes:
      - ./backend/app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    image: duynguyenngoc/apot:backend
    command: celery -A worker.celery.tasks worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./backend/app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis



  dashboard:
    build: ./backend
    command: ["celery", "flower", "-A  worker.celery.tasks", "--broker=redis://redis:6379/0", "--port=5555"]  
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
      - worker