version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - 8081:8081
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./backend/app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./backend
    command: celery worker --app=worker.celery --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./backend/app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build: ./backend
    command:  celery flower --app=worker.celery --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
      - worker